---
- name: Docker Installation
  hosts: demo
  become_user: root
  become_method: sudo
  become: yes
  tasks:
  - name: Install docker
    become_user: root
    become_method: sudo
    become: yes
    yum:
      name='docker'
      state=latest

  - name: service docker
    service:
      name=docker
      state=started
      enabled=yes
